version: 2.1

executors:
  rubocop:
    docker:
      - image: jobseeker/docker-library:ruby-2.4-rubocop
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

commands:
  rspec:
    steps:
      - checkout
      - run:
          name: Bundle dependencies
          command: bundle
      - run:
          name: Run tests
          command: bundle exec rspec
      - run:
          name: Simulate building the gem
          command: gem build *.gemspec

jobs:
  ruby_2_3:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - rspec
  ruby_2_4:
    docker:
      - image: jobseeker/docker-library:ruby-2.4-ci-node-bionic
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - rspec
  ruby_2_5:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - rspec
  lint:
    executor: rubocop
    steps:
      - checkout
      - run: pronto run -c origin/master --exit-code
  publish_gem:
    docker:
      - image: jobseeker/docker-library:ruby-gem-publisher
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /source
    steps:
      - checkout
      - run:
          name: Setup GitHub token
          command: GITHUB_TOKEN=$GITHUB_PACKAGE_PUBLISH_ACCESS_TOKEN /opt/github_auth.sh
      - run:
          name: Build (and release) the gem
          command: rake -f /opt/Rakefile release

workflows:
  version: 2
  rspecs:
    jobs:
      - ruby_2_3
      - ruby_2_4
      - ruby_2_5
      - lint:
          filters:
            branches:
              ignore: master
      - publish_gem:
          context: org-global
          requires:
            - ruby_2_3
            - ruby_2_4
            - ruby_2_5
          filters:
            branches: { only: master }
